Repository jfrog/setup-jfrog-cli, pull requests merged in 2024-05, with the labels that each got.

#147 Update JFrog CLI to 2.56.1
  action.yml
Labels: improvement

#151 Adding oidc token & parsed oidc user as action outputs
  .github/workflows/oidc-test.yml
  README.md
  action.yml
  lib/utils.js
  src/utils.ts
  test/main.spec.ts
Labels: improvement

#145 Github Job Summaries
  action.yml
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: new feature

#154 Add Job Summaries documentation
  README.md
  images/JFrog-Job-Summary.png
Labels: ignore for release

#156 Update version to 4.1.0
  package-lock.json
  package.json
Labels: ignore for release

#157 Update docs
  README.md
Labels: ignore for release

#158 Update docs
  README.md
Labels: ignore for release

#161 Fix job summary footer docs anchor
  README.md
  lib/utils.js
  src/utils.ts
Labels: bug
