Repository jfrog/setup-jfrog-cli, pull requests merged in 2024-12, with the labels that each got.

#227 Server configuration improvements
  README.md
  action.yml
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: improvement

#234 Revert default server ID removal
  lib/utils.js
  package-lock.json
  src/utils.ts
  test/main.spec.ts
Labels: bug

#236 Fix JFrog servers configurations cleanup
  lib/utils.js
  src/utils.ts
  test/main.spec.ts
Labels: bug

#232 Support application key configuration
  lib/utils.js
  node_modules/.bin/js-yaml
  node_modules/.package-lock.json
  node_modules/argparse/CHANGELOG.md
  node_modules/argparse/LICENSE
  node_modules/argparse/README.md
  node_modules/argparse/argparse.js
  node_modules/argparse/lib/sub.js
  node_modules/argparse/lib/textwrap.js
  node_modules/argparse/package.json
  node_modules/js-yaml/CHANGELOG.md
  node_modules/js-yaml/LICENSE
  node_modules/js-yaml/README.md
  node_modules/js-yaml/bin/js-yaml.js
  node_modules/js-yaml/dist/js-yaml.js
  node_modules/js-yaml/dist/js-yaml.min.js
  node_modules/js-yaml/dist/js-yaml.mjs
  node_modules/js-yaml/index.js
  node_modules/js-yaml/lib/common.js
  node_modules/js-yaml/lib/dumper.js
  node_modules/js-yaml/lib/exception.js
  node_modules/js-yaml/lib/loader.js
  node_modules/js-yaml/lib/schema.js
  node_modules/js-yaml/lib/schema/core.js
  node_modules/js-yaml/lib/schema/default.js
  node_modules/js-yaml/lib/schema/failsafe.js
  node_modules/js-yaml/lib/schema/json.js
  node_modules/js-yaml/lib/snippet.js
  node_modules/js-yaml/lib/type.js
  node_modules/js-yaml/lib/type/binary.js
  node_modules/js-yaml/lib/type/bool.js
  node_modules/js-yaml/lib/type/float.js
  node_modules/js-yaml/lib/type/int.js
  node_modules/js-yaml/lib/type/map.js
  node_modules/js-yaml/lib/type/merge.js
  node_modules/js-yaml/lib/type/null.js
  node_modules/js-yaml/lib/type/omap.js
  node_modules/js-yaml/lib/type/pairs.js
  node_modules/js-yaml/lib/type/seq.js
  node_modules/js-yaml/lib/type/set.js
  node_modules/js-yaml/lib/type/str.js
  node_modules/js-yaml/lib/type/timestamp.js
  node_modules/js-yaml/package.json
  package-lock.json
  package.json
  src/utils.ts
  test/main.spec.ts
Labels: ignore for release

#237 Upgrade JFrog CLI and set usage vars to be captured by JFrog CLI
  action.yml
  lib/utils.js
  src/utils.ts
  test/main.spec.ts
Labels: improvement

#239 Update CLI version
  action.yml
  lib/utils.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/utils.ts
  test/main.spec.ts
Labels: ignore for release

#235 Reduce `isHeaderPngAccessible()` timeout
  lib/utils.js
  src/utils.ts
Labels: improvement

#240 Update CLI version
  action.yml
  lib/utils.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/utils.ts
Labels: improvement
