Repository jfrog/setup-jfrog-cli, pull requests merged in 2024-07, with the labels that each got.

#172 Bump JFrog CLI version to 2.59.1
  action.yml
Labels: improvement

#173 Update Command Summaries docs
  README.md
Labels: ignore for release

#170 Fix color scheme not supported
  lib/utils.js
  src/utils.ts
  test/main.spec.ts
Labels: bug

#169 Add option to disable Job Summaries
  README.md
  action.yml
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: improvement

#174 Update version to v4.1.3
  package-lock.json
  package.json
Labels: ignore for release

#175 Make job summary disable input schema compatible
  action.yml
Labels: bug

#177 Add note about overriding build values
  README.md
Labels: ignore for release

#176 Reorder job summary sections
  lib/utils.js
  src/utils.ts
Labels: improvement

#178 Update job summary documentation
  README.md
  images/JFrog-Job-Summary.png
  images/job_summary.png
Labels: ignore for release
