Repository jfrog/setup-jfrog-cli, pull requests merged in 2024-09, with the labels that each got.

#185 Automatic `build-add-git` & `build-publish` on post job run
  .github/workflows/auto-build-publish-test.yml
  action.yml
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: new feature

#186 Command Summary - New UI
  .github/workflows/test.yml
  action.yml
  images/job_summary.png
  images/summary_header.png
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: new feature

#191 Bump version from 4.2.2 to 4.3.0
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: ignore for release

#193 Update documentation
  README.md
Labels: ignore for release

#192 Fix summary header image not loading
  images/job_summary.png
  images/summary_header.png
  lib/cleanup.js
  lib/utils.js
  src/cleanup.ts
  src/utils.ts
Labels: bug

#194 Fix Job Summary disabled on self hosted machines
  lib/utils.js
  src/utils.ts
  test/main.spec.ts
Labels: bug

#195 Bump version from 4.3.0 to 4.3.1
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: ignore for release

#197 Fix missing cached JFrog CLI path on cleanup task
  lib/utils.js
  src/utils.ts
Labels: bug

#199 Update Job Summary header
  images/job_summary.png
  lib/utils.js
  src/utils.ts
Labels: ignore for release

#201 Fix 'jf' path on cleanup and validate JobSummary supported CLI version
  .github/workflows/auto-build-publish-test.yml
  lib/cleanup.js
  lib/utils.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: bug

#204 Documentation Improvements
  README.md
Labels: ignore for release

#205 Fix connection check
  .github/workflows/auto-build-publish-test.yml
  lib/cleanup.js
  src/cleanup.ts
Labels: ignore for release

#208 Upgrade Default CLI version
  README.md
  action.yml
  lib/cleanup.js
  lib/utils.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/cleanup.ts
  src/utils.ts
  test/main.spec.ts
Labels: improvement

#210 Avoid throwing on JFrog CLI execution failures
  lib/utils.js
  src/utils.ts
Labels: improvement

#215 Set default JFrog CLI version to 2.68.0
  action.yml
Labels: improvement

#218 Improve build info default behavior documentation
  README.md
Labels: ignore for release
